FROM node:18 as builder
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY events/package.json package.json yarn.lock .yarnrc.yml ./
COPY events/package.json events/
COPY .yarn .yarn/

RUN yarn workspace @tumi/events install
COPY events events/
# If you are building your code for production
RUN yarn workspace @tumi/events build:ssr

FROM node:18
WORKDIR /root/
RUN npm install pm2 -g
# Bundle app source
COPY --from=builder /usr/src/app/events/dist dist
EXPOSE 4000
CMD [ "pm2-runtime", "dist/tumi-events/server/main.js" ]
