FROM node:18
# Create app directory
WORKDIR /usr/src/app
RUN apt-get update && apt-get install ghostscript graphicsmagick -y
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY server/package.json package.json yarn.lock .yarnrc.yml ./
COPY server/package.json server/
COPY .yarn .yarn/

RUN yarn workspace @tumi/server install
COPY server server/
# If you are building your code for production
ARG DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
RUN yarn workspace @tumi/server build:production
RUN npm install pm2 -g

#FROM node:16
#WORKDIR /root/
# Bundle app source
#COPY --from=builder /usr/src/app/dist dist
EXPOSE 3333
CMD [ "pm2-runtime", "server/dist/server.js" ]
