FROM node:18 as builder
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY legacy-app/package.json package.json yarn.lock .yarnrc.yml ./
COPY legacy-app/package.json legacy-app/
COPY .yarn .yarn/

RUN yarn install
COPY legacy-app legacy-app/
COPY shared shared/
ARG VERSION=DOCKER_VERSION
ARG CONFIGURATION=production
RUN sed -i "s|PROD_VERSION|$VERSION|g" legacy-app/src/environments/environment.prod.ts
RUN yarn workspace @tumi/legacy-app build --source-map --configuration $CONFIGURATION

FROM nginx:1.23.2-alpine
COPY legacy-app/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/legacy-app/dist/legacy-app /usr/share/nginx/html
COPY legacy-app/.well-kown /usr/share/nginx/html/.well-known
EXPOSE 4000
