FROM node:16 as builder
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY events/package.json package.json yarn.lock .yarnrc.yml ./
COPY events/package.json events/
COPY .yarn .yarn/

RUN yarn workspace @tumi/events install
COPY events events/
# If you are building your code for production
# RUN npm ci --only=production
RUN yarn workspace @tumi/events build:ssr
RUN yarn workspace @tumi/events build
#RUN yarn dlx @angular/cli build
#RUN yarn dlx @angular/cli run tumi-events:server

FROM node:16
WORKDIR /root/
RUN npm install pm2 -g
# Bundle app source
COPY --from=builder /usr/src/app/events/dist dist
EXPOSE 4000
CMD [ "pm2-runtime", "dist/tumi-events/server/main.js" ]
