FROM node:16
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY server/package.json package.json yarn.lock .yarnrc.yml ./
COPY server/package.json server/
COPY .yarn .yarn/

RUN yarn workspace @tumi/server install
RUN #yarn global add @angular/cli
COPY server server/
# If you are building your code for production
# RUN npm ci --only=production
RUN DATABASE_URL=${DATABASE_URL}
RUN yarn workspace @tumi/server build
#RUN ng run tumi-events:server

#FROM node:16
#WORKDIR /root/
# Bundle app source
#COPY --from=builder /usr/src/app/dist dist
EXPOSE 3333
CMD [ "yarn", "workspace", "@tumi/server", "start" ]
