FROM node:16 as builder
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY legacy-app/package.json package.json yarn.lock .yarnrc.yml ./
COPY legacy-app/package.json legacy-app/
COPY .yarn .yarn/

RUN yarn workspace @tumi/legacy-app install
COPY legacy-app legacy-app/
# If you are building your code for production
RUN yarn workspace @tumi/legacy-app build

FROM nginx:1.17.1-alpine
COPY legacy-app/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/legacy-app/dist/legacy-app /usr/share/nginx/html
EXPOSE 4000
