events {}

http {
    include /etc/nginx/mime.types;

    # Map hostname and path to favicon file
    map $http_referer $favicon_file {
        default /usr/share/nginx/html/favicon.ico;
        "~*tum-global-week\.esn\.world" /usr/share/nginx/html/favicon-tum.ico;
        "~*quties\.club" /usr/share/nginx/html/quties/favicon.ico;
    }

    # Map hostname and path to page title
    map $http_referer $page_title {
        default "ESN App";
        "~*tumi\.esn\.world" "ESN TUMi events";
        "~*mannheim\.esn\.world" "ESN VISUM Mannheim events";
        "~*tum-global-week\.esn\.world" "TUM Global Week";
        "~*quties\.club" "Quties Club";
    }

    server {
        listen 4000;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;

            # Set page title using sub_filter
            sub_filter '<title>ESN App</title>' "<title>$page_title</title>";
            sub_filter_once on;
        }

        # Serve favicon file
        location ~* ^/.*favicon\.ico {
            add_header Cache-Control "public, max-age=31536000";
            access_log off;
            expires 365d;
            alias $favicon_file;
        }
    }

    server {
        listen 4000;
        server_name app.quties.club;

        root /usr/share/nginx/html/quties;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;

            sub_filter '<title>ESN App</title>' "<title>$page_title</title>";
            sub_filter_once on;
        }

        location = /QUTIES_manifest.webmanifest {
            add_header Content-Type application/manifest+json;
            alias /usr/share/nginx/html/quties/QUTIES_manifest.webmanifest;
        }

        location ~* ^/maskable_QUTIES_x(192|512)\.png$ {
            add_header Cache-Control "public, max-age=31536000";
            access_log off;
            expires 365d;
            alias /usr/share/nginx/html/quties/$uri;
        }

        location ~* ^/.*favicon\.ico {
            add_header Cache-Control "public, max-age=31536000";
            access_log off;
            expires 365d;
            alias /usr/share/nginx/html/quties/favicon.ico;
        }
    }
}
