query loadSectionSettings {
  currentTenant {
    id
    communicationEmail
    currency
    homePageLink
    homePageStrategy
    seoDescription
    seoTitle
    settings {
      brandIconUrl
      timezone
      esnCardLink
      showPWAInstall
      enforcePolicyConsent
      registrationLimit {
        enabled
        period
        limit
      }
      sectionHubLinks {
        icon
        label
        url
      }
      socialLinks {
        icon
        label
        url
      }
      banners {
        displayToMembershipStatus
        link
        color
        body
        title
      }
    }
  }
}

mutation updateSectionSettings($id: ID!, $input: UpdateTenantInput!) {
  updateTenant(id: $id, updateTenantInput: $input) {
    id
    settings {
      brandIconUrl
      esnCardLink
      timezone
      showPWAInstall
      sectionHubLinks {
        icon
        label
        url
      }
      socialLinks {
        icon
        label
        url
      }
      banners {
        displayToMembershipStatus
        link
        color
        body
        title
      }
    }
  }
}
