configuration:
  activeRevisionsMode: Single
  ingress:
    external: true
    targetPort: 4000
template:
  containers:
  - image: ghcr.io/esn-tumi/app/legacy-app:main
    name: legacy-app-image
    resources:
      cpu: 0.25
      memory: 0.1Gi
  scale:
    minReplicas: 0
    maxReplicas: 3
    rules:
    - name: http-rule
      http:
        metadata:
          concurrentRequests: 500
